#!/usr/bin/env bash

# to  Update and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Update Nginx default server block to use custom 404 page
sudo sed -i '/error_page 404/c\        error_page 404 /404.html;' /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
