#!/usr/bin/env bash
# To Install and configure HAproxy on your lb-01 server.

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy

sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 147123-web-01 52.207.166.207:80 check\n\tserver 147123-web-02 54.234.64.6:80 check\n' /etc/haproxy/haproxy.cfg
service haproxy restart
