#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 100.26.120.186
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
